# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82819149e0a0c498e97765eefd259adcb21eeddca776953363f3244b7d78c8db1a022d33fb34a68b494ecc20479d301c11d58791f5b9bfe7e3d73c4e588932e8

test:
  secret_key_base: e3c728283f254b2c28fc452cbdc26d31481d0a6537e27d397d270f066a6c078592a8cc021754e0303c0113235e94af19853a7bf28a241f3df48d6cd4fb1d3468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
